In [10]:
import numpy as np
from scipy import linalg

## Matrix Operations
1. Write Python code for addition, subtraction, multiplication, element-wise multiplication, determinant, the inverse of the matrix using NumPy and SciPy package.
    - Addition
    - Subtraction
    - Multiplication
    - Element-wise Multiplication
    - Determinant
    - Inverse

In [3]:
# use numpy to create sample matrices
# the following are 2x2 square matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A: \n", A)
print("Matrix B: \n", B)

Matrix A: 
 [[1 2]
 [3 4]]
Matrix B: 
 [[5 6]
 [7 8]]


### Matrix Addition

In [4]:
result = np.add(A, B)
print("Result of Matrix Addition: \n", result)

Result of Matrix Addition: 
 [[ 6  8]
 [10 12]]


### Matrix Subtraction

In [6]:
result = np.subtract(A, B)
print("Result of Matrix Subtraction: \n", result)

Result of Matrix Subtraction: 
 [[-4 -4]
 [-4 -4]]


### Matrix Multiplication

In [7]:
result = np.dot(A, B)
print("Result of Matrix Multiplication: \n", result)

Result of Matrix Multiplication: 
 [[19 22]
 [43 50]]


### Matrix Element-wise  Multiplication

In [8]:
result = np.multiply(A, B)
print("Result of Matrix Element-wise Multiplication: \n", result)

Result of Matrix Element-wise Multiplication: 
 [[ 5 12]
 [21 32]]


### Matrix Determinant

In [15]:
result = linalg.det(A)
print("Determinant of A: ", result)

result = linalg.det(B)
print("Determinant of B: ", result)

Determinant of A:  -2.0
Determinant of B:  -2.0000000000000036


### Matrix Inverse

In [17]:
try:
    result = linalg.inv(A)
    print("Inverse of A: \n", result)
except linalg.LinAlgError:
    print("Matrix A is singular and cannot be inverted.")

Inverse of A: 
 [[-2.   1. ]
 [ 1.5 -0.5]]


## Eigenvalues and Eigenvectors
2. Write Python code to calculate eigenvalue and eigenvector of a matrix. Check the orthogonality of the eigenvector.
    - Eigenvalue
    - Eigenvector
    - Orthogonality Check

In [24]:
# symmetric matrix
m = np.array([[6, 9], [9, 6]])
print("Symmetric Matrix: \n", m)

Symmetric Matrix: 
 [[6 9]
 [9 6]]


In [25]:
eigenvalues, eigenvectors = linalg.eig(m)

print("Eigenvalues: \n", eigenvalues)
print("Eigenvectors: \n", eigenvectors)

Eigenvalues: 
 [15.+0.j -3.+0.j]
Eigenvectors: 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [27]:
# check for orthogonality of eigenvectors
# eigenvectors are orthogonal if their dot product is zero.
dot_product = np.dot(eigenvectors[:,0], eigenvectors[:,1])
print("Dot Product: ", dot_product)

Dot Product:  0.0


## Span and Basis Calculation
3. Calculate span and basis of a vector space using Python.

In [28]:
from scipy.linalg import orth

In [29]:
# matrix where columns are vectors
vectors = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]).T
# transpose: rows -> columns
# why? vectors are expected to be in columns for operations.

In [30]:
print("Sample Vectors are: \n", vectors)

Sample Vectors are: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [40]:
# basis is the minimal set of vectors needed to represent the entire space
basis = orth(vectors) # calculates orthonormal basis
print("Basis for the vector space: \n", basis)

Basis for the vector space: 
 [[-0.47967118  0.77669099]
 [-0.57236779  0.07568647]
 [-0.66506441 -0.62531805]]


In [39]:
# span represents all the linear combinations of the basis vectors
rank = np.linalg.matrix_rank(vectors)
print("Dimension of the span: ", rank)

Dimension of the span:  2
